var payload = new Memory(`
  
Off The Grid
  Water
    & In most dry places, desalinated potable water is free or available for cheap. In most tropical islands, potable water is available but often scarce, and so it is best to {*catch rain water*} which can then be treated with bleach: 1/2 tsp for every 5 gallons.
  Showers
    & Coastal locations like marinas and public beaches often have fresh water showers for local swimmers or marina guests. Usually free, or available for use at a nominal fee.
    & We also carry a <a target="_blank" href="https://www.amazon.com/gp/product/B0009PUT20/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0009PUT20&linkCode=as2&tag=hundredrabbit-20&linkId=6a58773485c039406a82ee6540a3d8d7">Solar Shower</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B0009PUT20" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, a black pouch hung outside and made warm by sunlight. We will often simply {*bathe in salt water, and rinse with fresh water*} from a spray bottle in locations where water is scarce.
  Provisioning
    & While modern grocery stores can be found in larger cities, these can often be far apart. In smaller towns, fresh vegetable and fruit markets are seldom open everyday, most only once a week.
    & For remote places, {*canned, dried or shelf-stable foods are a good alternative to refrigeration*}. Choosing canned foods is something worth experimenting with - buy an assortment, find which suit your tastes. We usually look for unsalted ones, without corn syrup.
    & Our favourite canned vegetables are mushrooms, mixed beans and tomatoes. Our favourite dry foods are nori, oats and cornmeal. Our favourite shelf-stable foods are tetrapak tofu, spicy sauces and various japanese condiments.
  Medical
    & Most city-centers will have a hospital, but in most cases you must be self-sufficient. That includes a well-stocked medical supply and the know-how to fix yourself up. In case of a serious injury, you must have the means to get yourself to the nearest clinic. We use {{DAN Boater|http://danboater.org}}, a {*repatriation insurance*} that covers helicopter/transportation fees.
    & We find that {*medical apps for mobiles, and FM armyfield manuals*}, are helpful when dealing with minor burns, cuts and various aches.
  Books
    & While books are great, they take up a lot of space, are prone to mold, and in warm countries, they ultimately attract insects. To protect them from moisture, we have resorted to {*keeping them in ziplock bags*}.
    & Amongst sailors, and likely other types of nomads, books and movies are a trading currency. Social hubs will often have bookshelves inviting you to take and leave a book. We have found countless gems in those.
    & Most of our books now, are on our <a target="_blank" href="https://www.amazon.com/gp/product/B00OQVZDJM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00OQVZDJM&linkCode=as2&tag=hundredrabbit-20&linkId=7a4a9d64023b1a0b4bb257d1e43dc00c">Kindle Paperwhite</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B00OQVZDJM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, which takes little battery and allows us to read at night.
  Internet
    & We often find ourselves away from hotspots, and even cellphone reception. We try, as much as possible, to send periodical location updates to our families. We use a satellite phone operating on the Iridium satellites network to do that.
    & The {*Iridium Go satellite phone*} costs around about 100US$/month and allows us to keep in touch with our friends and families via SMS & emails, from anywhere in the world - even the middle of the ocean.
  Visas
    & Some countries require visas in advance, most do not, this also depends on your nationality. The visas are generally free, unless you require an extension for your stay. Upon entry into a new country, you may need to pay the immigration, customs, health and quarantine officers.
    & Upon leaving, a departure tax and varying amounts based on the size and weight of your vessel might also need to be paid. These fees can sometimes total up to 200US$. We find {{Noonsite|http://noonsite.com}} to be a good resource for country-specific information on fees.
  Money
    & Most places that we have visited do not necessarily have ATMs, but always have a bank nearby that will take a VISA card.
    & Better make sure that your credit card will not be blocked when used in foreign countries, and that it will expire at a location that will allow for you to receive a new one.
  Budget
    & Provisioning can be expensive in certain countries, so stocking strategically with cheaper stores, ahead of time, can help to save money.
    & Canning is essential when traveling on a budget, a pressure cooker and glass jars will save you money and will help reduce waste. Preparing your own stores, also means that you choose what goes in it, therefore reducing your intake of added salts and sugars.
  Essentials
    & Being in good physical shape is important, wether you need to run, jump or lift something heavy without injuring yourself. Knowing how to tie solid knots is paramount, knowing how to tie a good {bowline knot} could save your life.
    & A good stainless-steel {*knife*}, a spindle of {*paracord*}, a phone-size {*ziplock bag*}, a waterproof {*flashlight*} and a good {*drinking bottle*} for fresh water will go a long way.
  Nutrition
    & Following a {{plant-based diet|http://grimgrains.com}} while traveling is possible. Planning provisions ahead is important, a lot of the places may not have specialty items. We found nutritional yeast, miso, flax seeds and B12 supplements, especially hard to find.
    & Buying a large supply of shelf-stable tofu is always a good idea; as it is a complete protein that can be used to make sauces and sautees, while providing calcium. Carry iodized salt, or items with iodine like seaweed.
    & Staples like nut milks and oats are found everywhere, varying in price and quality. There will always be fresh vegetables available, but the selection can be poor at times. Carrying cans and and dried version of those foods can help, for example: canned and dried potatoes. Canned spinach may not be appealing, but in a place where there are no leafy greens available, it's better than not having any at all.
  Distractions
    & When at anchor, it can sometimes be difficult to stay focused. The weather is king, it determines whether or not we can work. If the weather is foul, we are on anchor-watch to make sure we don't drag.
    & Waves also makes it hard to do simple tasks like writing, or drawing. Depending on the direction of the wind, we need to move the boat and that too, takes focus and time away from work. Calm and sunny days, are distracting in other ways: when the water is clear and teeming with colourful fish, it is difficult to resist jumping off.
    & It is easier to work on projects when docked, as we need not worry about the weather or the charge of our batteries.
  Internet
    & Since connectivity can be rare, and far apart, the time that we do have online is spent wisely. Uploading backups, responding to requests from users, updating our friends and families with our new location.
    & As cellular data is often expensive around islands, disabling autoplay on videos, and disabling image previews is near obligatory.
  Work
    & Working online without a constant internet connection is feasible, but painful. Still, there are ways in which some of the friction can be removed from the process.
    & Getting local SIM cards, with blocks of data, works well within cellphone reception range. But in the constraints of expensive cellphone data, uploading large files can be made possible by offloading heavy-lifting onto remote servers; having your {*server build and upload your projects*} instead of using your laptop batteries and broadband.
    & There is no solution to uploading videos to youtube, it's a costly and lenghty process. We have made the decision to keep our videos under 5 minutes to help reduce upload time.
  Troubleshooting
    & Tools like {*Offline Wikipedia, digital encyclopedias and dictionaries*} a great assets to have aboard. Recipes can often be devised from dictionary descriptions of foreign fruits and vegetables.
    & In the case of a nomad programmer, having the current {*programming language documentation & various source files*} is an asset. Prior to going offline for a few days, we often rip entire sites, or capture specific pages as webArchives. The same goes if drawing references are needed, projects are planned ahead and references are collected while a good internet connection is available.
  On documentating
    & We use a <a target="_blank" href="https://www.amazon.com/gp/product/B01LZTLCFX/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LZTLCFX&linkCode=as2&tag=hundredrabbit-20&linkId=fec2820c58bc37ea0246837013c44025">GoPro Session4</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B01LZTLCFX" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> as well as a <a target="_blank" href="https://www.amazon.com/gp/product/B00I8BICB2/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00I8BICB2&linkCode=as2&tag=hundredrabbit-20&linkId=4953ab6afe6012d425ce93d66affeda0">Sony a6000</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B00I8BICB2" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> to film our travels. The GoPro has the advantage of being {*light and waterproof*} - making for a perfect everyday-carry camera. Shooting with the SLR requires more planning as it can only used in fair weather.
    & We film as much, and as often as we can. At the end of each month, we watch our footage and write a summary of that month's events. Monthy capsules are planned ahead, and we gather footage based on what is needed. While one is busy recording the narration, the other writes music, the two tracks are then edited together with the collected footage. We have our respective tasks when it comes time to edit, but both of us take part in the filming.
    & In rough weather, we prioritize our own safety above all, and so we rarely have footage of rough seas.
  Computers and software
    & Salt water is highly corrosive, even an open window can let in salt air and long term, it can damage electronics. The usb ports of our laptops, as well as our usb cables have suffered damage as a result of this. We now store all devices and cables away after use, in large plastic containers. Since we use our phones for navigation, or to listen to music outside, we keep them in protective sleeves.
    & Having backups for your devices is of the utmost importance, extra power adaptors and mini usb cables are a must. Extra computers is also recommended, especially if you are working somewhere where new hardware is impossible to find, or too expensive.
    & If you can work on a machine that costs less money, do it. If something happens to it, it wont be too complicated to replace. Macbooks consume a lot of energy, and battery life is always an issue. Power consumption is something that should be taken into account when choosing a computer for working at sea.
    & We use a <a target="_blank" href="https://www.amazon.com/gp/product/B076BWPZC3/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B076BWPZC3&linkCode=as2&tag=hundredrabbit-20&linkId=f3e949635aedc2213fed80d525fd7b56">Samsung Chromebook 11.6’’</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B076BWPZC3" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> to do our writing work, it is also our media station. We work on macbooks, but would like to change this in the future. Using an Ipad for sketching and drawing is a good solution, as is using {{Ronin|https://hundredrabbits.itch.io/ronin}} which uses less power than photoshop.
    & We have a <a target="_blank" href="https://www.amazon.com/gp/product/B01789QMUW/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01789QMUW&linkCode=as2&tag=hundredrabbit-20&linkId=915a1e69d9e11c7faee8a8d743825db1">La Cie Rugged Portable Hard Drive</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B01789QMUW" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> that is waterproof and shockproof, we store all of the footage we shoot as well as backups of files that had not yet been uploaded online. 
    & Rekka uses an ipad 2 with autodesk sketchbook for concept art, and draws using fingers instead of a pen (fingers are just as precise). Finished work is done on a macbook pro, the files are transferred via usb and then moved to desktop using {{IExplorer|https://macroplant.com/iexplorer}} (using the demo version). The work is finished in photoshop, using an intuos 4 tablet.

On buying a sailboat
  On having a floating home
    & When living on the water, your home is always in motion, swaying with the currents and winds. Knowing that your vessel is not permanently tethered to the earth is a good feeling, it means you can go anywhere. 
    & I've always had difficulty taking public transportation, I don't have a driver's license either. My primary mode of transport has always been a bicycle, it's quiet, and I'm free to move myself around wherever, and whenever I want. Traveling by sailboat, is taking this a step further, you can move yourself over from one continent to the other. 
    & If you want to live in a sailboat, you don't have to sail offshore. There is much to be experienced and seen while staying in one country, but at least, if you have the itch to leave, you can do it. There are many other benefits to having a floating home.
  Why live on a boat?
    & 1. {*The scenery changes everyday*}. If you're at anchor, the boat turns with the wind and you find yourself with a new view. If you don't like your neighbours, you have the option of hauling anchor and moving somewhere else - having the freedom to move from place to place unhindered is wonderful. 
    & 2. {*You have a small ecological footprint*}. A boat is a gateway to self-reliance, with systems completely off-grid. With solar you consume no power, with wind propulsion there are no emissions, and because water is limited to your tanks, you are aware of how much you use; awareness is key. 
    & 3. {*Low-cost home ownership*}. For a lot less money, you can own something and make it yours. You can anchor in downtown Vancouver for free, and share the same view as the million dollar condos lining the shore. 
    & 4. Y{*ou can travel with your house.*} This is ideal for us, as artists, to be able to go to different places while our cocoon stays the same. 
  What boat to buy
    & When we began looking for a sailboat to buy, we'd spend evenings browsing listings on yachtworld, trying to figure out what sort of vessel best suited our needs and budget. But here are some questions you should ask yourself first to help narrow your search:
    & 1. {*Budget*}. What is the max amount of money you're willing to spend on a yacht. Be realistic, be cautious. Keep in mind that you will probably put a lot more money into it afterwards, even more if you plan to take it offshore. There is a yacht out there for any budget, but it's important to remember that the cheaper it is the more time and work you will have to put back into it. If time is a factor, you may prefer to pick a turn key yacht. If you have a limited budget, choosing a smaller boat is a smart move. Dock fees are priced on boat length, and every bit of gear gets more pricy when sized up. 8-11m is the sweet spot when it comes to boats.
    & 2. {*Location*}. Where do you want to be cruising/living? Depending on your goals, it may be better to buy the boat in another country; although this comes with its own set of complications. If you don't have much experience, you're better off choosing a boat near your home grounds. You won't have to deal with visas that way. For example, we moved to Vancouver from Montreal to get Pino, it was a good choice and still relatively close to home.
    & 3. {*Experience*}. If you're a novice, starting out smaller is a better idea. Smaller boats give more immediate feedback, you get a feel for the wind and are less likely to make costly mistakes on a larger yatch afterwards. 
    & 4. {*Comfort*}. A larger boat is more comfortable on a passage. Race boats (tall rig), like ours, tend to heel quite a bit. You get used to it, but it may not be ideal for you. 
    & 5. {*Intentions*}. If you want to travel the world, your yatch will need to be suitable for rougher waters and stronger winds. There is not just one type of blue water boat, you will have to familiarize yourself with the features required for offshore travel. We recommend reading {{Seaworthy Offshore Sailboat|https://www.amazon.com/gp/product/007137616X/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=007137616X&linkCode=as2&tag=hundredrabbit-20&linkId=31b32cfe5726928783254fd1365fc06c}} by John Vigor.
  I found a boat. What now?
    & Visit the boat, inspect every inch of it and take plenty of photos and/or videos. If you know anyone with experience on boats, have them come with you, or show them the listing/photos afterwards and ask them what they think. If you think you've found your forever boat home, make an offer. Usually, this is done through a sales agent. 
    & If your offer is accepted, the next step is to have a survey of the boat done. The yacht is hauled out of the water, and checked by a marine surveyor. In turn, you receive a document with every detail of the boat, which includes photos and a list of items that need to be looked at/replaced. To buy Pino Devine & I each got a 10,000$ bank loan. We had savings, but didn't want to be left with an empty account after the purchase. That proved to be wise, given the cost of everything marine - we had no idea how bad it was. We made a plan then, to pay off the loan within 3 years, which amounted to payments of ~600$ a month.
  Getting certified
    & You can get a boat without experience (like we did), but in Canada you need a couple of things first.
    & 1. {*Pleasure Craft Operator Card*}. The test is easy, and covers the basic safety regulations, as well as buoyage. You can do the test online, and the card will be shipped to you afterwards. This test makes sure that you understand how to recognize different buoys, how to navigate alongside other boats etc.
    & 2. {*A ROC certificate*} (radio operator's certificate). You need this to be able to operate a marine VHF radio. Check your area for ROC courses, it costs about 100$ per person. You can buy the manuals and study at home, then take the test on a scheduled date with an examiner. The test is a multiple choice written exam, and includes a few verbal questions about radio calling (need to learn {{Nato Phonetic Alphabet|https://en.wikipedia.org/wiki/NATO_phonetic_alphabet}}). You have to take this test, otherwise you won't be permitted to transmit on the radio (you can technically, but you will be in the wrong). Knowing how to talk on a VHF radio is important, especially if you've had an accident and need help.
    & 3. {*Security gear*}. Even if you're just going for a short outing with your boat, you need to get basic safety gear, like lifejackets (one for every person aboard), a medical kit, a PLB or EPIRB, good {{ground tackle|#ground tackle}} etc.
    & 4. {*Changing your boat name*}. First of all, ignore whatever anyone tells you about it being bad luck; Neptune doesn't give a shit. Having a name that means something to you is important. In Canada, changing your boat name will cost you 250$ and the wait time varies, 1-2 months. You can visit {{Transport Canada|http://www.tc.gc.ca/eng/marinesafety/oep-vesselreg-registration-menu-2311.htm}} for information on how to do it. They will send you a certificate of registry, this piece of paper is very important. You will have to show it to customs whenever you're entering a new country by boat.
  Go sailing
    & If you already know how to sail, good on you! Otherwise, here is what you can do:
    & 1. {*Get lessons*}. If you can afford lessons, do it. It will make you a more confident sailor. 
    & 2. {*Hire a captain*}. Again, if you can afford it, the best thing to do would be to hire a captain to teach you how to sail your own boat. All boats are different after all.
    & 3. {*Go race*}. Go to yacht clubs and volunteer to race on boats, you don't have to be part of the club to do this most times. You will learn a lot doing this. People who race push their boats to the limit, you can see how different boats behave and what not to do. 
    & 4. {*Join a yacht club*}. Just spending time in the lounge or in organized outings is great. Making sailing friends is important, we learned a lot that way. 
    & 5. {*Just get out there!*} Once you know the basics, go out with your boat as much as you can and practice.
    & For the novice, there are many sailing {*manuals*} you should read. The first time we pushed off the dock, we didn't even put the sails up. Picking a calm day to make your first outting is probably a good idea. Also, if your boat is in a river, go out at slack tide. Don't be afraid to ask others for help. Walk around the docks, ask questions, make friends. Sailors like to share knowledge, they will be happy to help. No question is a stupid question. 
  Going offshore?
    & If you want to go offshore, there is a long list of safety items, tools and spares that you need to have. 
    & When we planned to leave Canada, we met up with some racers who were going to do the Vic-Maui race. They gave us their {{vessel and equipment checks list|https://www.vicmaui.org/official-notice-board}}. These are all things that you will need at some point or another. Depending on your sailing plans, it may be tough to find spares, and so it is best to leave with almost everything now.
    & Another helpful reference document for gearing up for offshore travel, is the {{New Zealand Cat 1 requirements list|https://astrolabesailing.com/2014/03/24/yachting-nz-cat-1/}}. New Zealand registered yachts can't go offshore without passing a Cat 1 survey, if they don't pass, they can't leave.

Liveaboard
  Habitat
    & As with most things in life, 20% of anything does 80% of the work. When moving into a smaller space, it is important to find that 20% and surround yourself with things purposefully. Single-serving tools and kitchenware will not do.
    & Investing in good quality {*army blankets and waterproof sleepingbags*} will make a world of difference. Non-metallic(bamboo or ceramic) kitchenware is also essential, everything rusts on a boat - even stainless-steel. To keep our clothes dry, we store them in large sealed industrial plastic containers.
  Toilet
    & We have a salt-water {_head_} which looks much like a household toilet, but with a handle on the side, that pumps water in and flushes it out into a holding tank. The holding tank can be emptied in the ocean when far from shores, or at marina pump-out station for free. The latter option being the best, seeing as how pump-out stations also have fresh water hoses, which can be used to flush out the tank.
  Costs
    & Living at {*anchor*} - that is, in a bay somewhere tethered to the earth with ground tackle, is usually {*free*}. Some bays will have {*moorings*} installed, that can be used for a {*small fee*} (often around 10-15$.) Marinas often have guest {*docks*} with power, wifi and showers, for a {*medium-to-high cost*} (400$-600$.)
  Navigation
    & The entire task of navigation rests upon the {*Navionics*} app, installed onto all of our mobile devices. Its depth maps, compass, GPS, waypoints, community edits, and more, are all the features that we could ever wish for to get from A to B, over water.
  Insects
    & We have had a few encounters with insects aboard, often from food bought in small town groceries. Thin plastic bags, paper bags or cardboard should be avoided, or discarded prior to entering the boat.
    & We {*wash all vegetables, and fruits*}, with a 1:1 water and vinegar solution in a spray bottle, and rinse them in fresh water thoroughly. We leave them out to dry before storing them inside, moisture accelerates rot. 
  Night time
    & During long passages, we must sail throughout the nights. Our pattern, for two crew, is one sleeps between 1900 and 2100, then sails between 2100 and 2400, then goes back to sleep from 2400 until 300, and then goes back to the wheel between 300 and 600.
    & During these long nights, we listen to countless podcasts and audiobooks, which we discuss around breakfast in the morning. If we're feeling especially tired, listening to upbeat music, as opposed to spoken content helps.
    & During long passages, our daytime sailing occupations include: cooking, cleaning, doing fixes on the boat and brainstorming on future projects. We don't have a tight schedule for watches, we hand the wheel to the other as we get tired.
  Weather
    & Our favourite weather service is {{Windy|http://windy.com}}, and while underway, we download weather maps(.grb files) through the {{saildocs|http://saildocs.com}} service with our Satellite Phone which we then process with {{PredictWind|http://predictwind.com}}.
  Water storage
    & Our main tank carries 170L, while an additional 150L is stored in jerry cans. When it is not possible to dock at a marina, we use smaller(4x10L) jerry cans to ferry water from shore. While it requires more trips, the lighter containers are less prone to breakage.
  Electricity
    & We have 4 Solar Panels(1 x 60W, 1 x 100W and 2 X 90W). For additional power, we also carry a Honda EU1000i generator. Our boat has a 75AMP Balmar alternator, but it is only used when we need to use high-power systems like the macerator and the windlass. Every single light is LED, cutting down the consumption of power, from lights, by 10 compared to halogens.
  Radio
    & As a sailor, you {*must offer help*} to a boat in trouble. Radio communication is key, specific channels are used in every country for emergencies or information exchange. Every morning, sailors will tune in to a specific channel and listen to a {*morning net*}, a public radio exchange in which the weather and local events are announced, as well as boats seeking crew, or items that need to be sold or found. When the weather is foul, the local channels are very busy.
  Comraderie
    & There is an unspoken understanding between sailors, an exchange of looks when foul weather is amidst. All know the difficulties of life at sea, and is ready to lend a hand. We refer to each other by boat name, and like a bird-watcher, we can identify rare breeds by sight. When transiting through world routes, the same boats, you will meet many times, thus strenghtening the connection.
  Schedules
    & We sail on a loose schedule, our movements are tied to the weather. We follow the seasons and prevailing tradewinds, to save on fuel and to avoid seasonal storms. We make stops for re-provisioning and rest.
    & It has taken us a little more than a year to cross the Pacific Ocean. And while it may have cost us time, it earned us safe passage, and our many stops have helped to broaden our view of the world.
    & There is 11,707 km (6321nm) between Vancouver and Auckland, this transit could be accomplished in approximately two months of non-stop sailing days, but where would be the fun in that.
  Privacy
    & There is none, it is something you must prepare for. If you are to travel for extended periods of time with another person, you must be compatible. You must discuss problems when they arise and express concerns right away.
    & The combined space, below and atop deck, is bigger than it seems. If you are near land, there is always the option of going for a walk.
  Laundry
    & In populated cities, laundry can be carried ashore to a laundry mat. In the south pacific, you will have to take care of it yourself. We use rain water to wash our clothes, by hand, using a set of buckets and a brush. The clothes are brushed and washed in soapy water once, then rinsed in fresh water.
    & When underway during a long passage, we do a salt water wash to save water, and rinse with fresh water. The clothes is hung out to dry on the lifelines, or on a separate line that we set up. Leaving dark clothes out to dry in the sun will cause it to discolour faster, such is the cost of sailing in warm places.
  Washing dishes
    & We bring the dishes outside and wash them with saltwater scooped up from the side of the boat, using a bucket attached to a rope. The dishes are then rinsed inside with our fresh water foot-pump.
    & The fresh-water foot-pump pulls water from our tanks and dispenses it to the galley's sink at the rate of approximately a 1/4 cup per push. This system allows us to calculate water-consumption and storage.
    & We have a water pressure system onboard, but we chose not to use it since it dispenses more water.

Sailing
  Slow and steady
    & If you can do the same speed with less sail, do it. As soon as you think of reefing down, do it. Should we reduce sails? yes, always yes.
    & Better be safe than sorry. Reefing early will save you a lot of problems, shaking out a reef is easier than putting one in in big winds.
  No schedules
    & Sailing with a schedule is a recipe for disaster, too many things can happen on a boat and arriving on a precise date can be difficult. Making plans will make you do bad decisions, leaving in bad weather to make a meeting for instance, can be dangerous.
  Ground tackle
    & Our anchor is sized to our boat, we have a <a target="_blank" href="https://www.amazon.com/gp/product/B00LY6OFS2/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00LY6OFS2&linkCode=as2&tag=hundredrabbit-20&linkId=0f215b9ce11f64f8277d437bd4c9e57e">Rocna 22 lbs (10 kg)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B00LY6OFS2" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />. Some will argue that bigger is better, but in our experience the quality and shape of the anchor, as well as your scope makes all the difference. If you want to upsize, your bow roller may need replacing, and in the event of windlass breakage, heaving it up by hand could be next to impossible. We also carry a Bruce 10, with extra lenghts of chain and rope.
    & We carry 30.5m of chain on {{Pino}}, with 61m of 3-strand nylon. This means that we anchor safely in waters no deeper than 11m, we have found plenty of anchorages in the south pacific in that depth range.
  Eliminating electricity
    & Our aim is to have as few items as possible on board that demand power. We would like to have a manual windlass, and a composting head. A manual windlass would use no power at all, and eliminate all wiring, thusly minimizing the possibilty of corosion. A composting head would eliminate the need for a macerator, and for a sceptic tank. Our sceptic tank is 113 L, if we could get rid of it we could replace it with 113 L of fresh water instead.
  No refrigeration
    & We have stopped running our refrigerator onboard, because of power constrainst. We don't drink nut milks anymore, because the average-sized tetrapak containers don't stay fresh for more than 3 days. We've wasted too much nut milk, having none aboard is better and we've managed well without it.
    & Most condiments don't need refrigeration, then again we don't use any dairy-based products or items like ketchup. Hot sauces, soy sauce, all vinegars, mirin, jam, lemon juice and other items, if used regularly, will fair just fine in cupboards.
    & Refrigerated vegetables will rot faster, but leaving them out and wiping off the excess moisture will help. Buying market vegetables that have never been refrigerated are best - root vegetables will last an especially long time. Items like peppers and leafy greens will spoil quickly, and should be eaten first.
    & Leftovers we eat the next day, incorporating it into other meals to offer some variety. Preparing food in the pressure cooker, and letting it rest unopened will help preserve the food. If left overnight, it can be reheated in the morning and will keep well until lunchtime.

Used goods
  Swap meets
    & Swap meets are events when sailors will gather and sell items they have and no longer need. The prices are good, and sometimes you can trade. There are a lot of these events in places where foreigners on yachts tend to gather. We attended swap meets in La Paz (mexico), Vava'u (tonga) and soon we'll go to the one in Whangarei.
  Used marine goods
    & If you live in a big city with lots of sailors and marinas, chances are there will be a good used marine goods shop around. Many cruisers opt to sell their gear there or to put their items on consignment (thusly eliminating the need to actively search for buyers).
    & If you know what you are looking for, you'll most likely find it, or you'll find something very near to it. Second hand shops are full of bins consisting of cryptic metal parts and angry tangles of wire, the quantity and diversity of it all can be quite intimidating. We have often left more confused than we started, it's for this reason that you need to enter stores like this with a plan.
    & Stores like this will often sell used sails too, even sail shops sometimes have some pretty sweet deals.
    & Examples:  Stanley Marine in Whangarei, Blue Pelican in San Francisco, Minney's yacht surplus in Costa Mesa etc.  
    & *Note that all of these places have big yacht concentrations. The more boats there are, the more used gear you will find.
  Local notice boards
    & It's a good idea to look at marina notice boards when foreign yachts start populating your area. We've seen many ads with amazing deals: lots of cheap dinghies, outboards, paddle boards etc. More often than not, people are just passing through and want to get rid of items quickly.
    & We walk by the marina office everyday, and always stop to look for new notices. This is how we got our extra solar panels. We purchased two 90W {{solar panels|#electricity}} for 150$ from an older English couple, they sold these panels to upgrade to larger models (they have more electronics and toys than we do). We've installed them already and they work perfectly, the owner of the boat even came to help us set them up (the sailing community is awesome like that). 
  Marina trash
    & Every time we bring recycling to the marina bins, we look at the trash to see if there are any goodies. The other day we found a working 600W inverter, with american-style outlets. Chances are the owner wanted to upgrade to a higher wattage, and didn't think it worth while to sell this one (given the voltage). There aren't that made north american yachts passing through NZ on a yearly basis, and the ones that are there are not necessarily looking for inverters (most yachts need bigger inverters than this). This was a godsend for us, we needed to upgrade our little 250W. Now we can charge both of our laptops at once (yay).
    & If you keep your boat near a big city where lots of racers congregate, chances are the marinas in the area will have bins with lots of good gear. Racing yachts are particular about their boats, some count the number of tacks they make and replace the sail when they reach a certain number. I imagine the sail's performance may be reduced, but to a cruiser or tinkerer, there are many things one can do with an old sail. Friends of ours have found great-looking sails in trash bins around big marinas in Auckland.
    & We've seen entire boat ovens, rigging wire and jabsco toilets in bins. While these items may not be working, sometimes you can salvage parts. We've collected many items over the past 2 years, we almost always find a use for them*.
    & *Note: in no way do we want to become hoarders, it's important to be selective in your findings. Otherwise, after a year of accumulation, it's always a good idea to review what you have and to get rid of stuff. {{Swap meets|#swap_meets}} are great for that.
  Thrift stores
    & Back when we lived on land, we moved a lot. Instead of purchasing new items, we would get them at thrift stores and then return the items when they were no longer needed. In Montreal, we purchased items from Les Petits freres, a store who's proceeds goes into helping the elderly. They could help themselves to items in the store for free. The items you give and take serve a much greater purpose than you think.
    & Recently, Devine & I wanted to buy a sewing machine so we could do some projects on the boat. Most of the machines we saw in store didn't fit our budget. There is also the fact that we have limited knowledge of such things, and turned to our sailing friends for model suggestions.  
    & Most of the people we know carry a sailrite, a heavy-duty sewing machine (that weighs as much as we do) with which you can do sail and canvas repair. Buying a new sailrite will cost you anywhere from 650-1300$US dollars, if you consider the cost of sail repair it is a good deal (but not one we can afford).
    & We settled on a Toyota sewing machine for 35$, bought in a second-hand shop. With it we can do repairs to canvas and cushions, not certain if it'll work for sail repair but we'll give it a shot. Otherwise, nearly every north american sailor carries a sailrite, we'll make friends and ask to borrow theirs. We did this while in San Francisco, and repaired our mainsail cover with it. It never hurts to ask, and sharing is nice isn't it?

Resources
  Manuals
    - <a target="_blank" href="https://www.amazon.com/gp/product/1929214340/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1929214340&linkCode=as2&tag=hundredrabbit-20&linkId=5f516eb82cb6b960fbbef4ed8fc0c8c5">The Care and Feeding of the Sailing Crew</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=1929214340" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Pardey
    - <a target="_blank" href="https://www.amazon.com/gp/product/0964603675/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0964603675&linkCode=as2&tag=hundredrabbit-20&linkId=8afbef1bf14988f979b15292b6c347be">Self Sufficient Sailor </a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=0964603675" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Pardey
    - <a target="_blank" href="https://www.amazon.com/gp/product/0957262647/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0957262647&linkCode=as2&tag=hundredrabbit-20&linkId=0e04161ead7a3732676aa99304093f69">World Cruising Routes</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=0957262647" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Jimmy Cornel
    - <a target="_blank" href="https://www.amazon.com/gp/product/B00IGYQV6E/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00IGYQV6E&linkCode=as2&tag=hundredrabbit-20&linkId=ea2bd07760b8ce0aec61413c125494a5">How to Sail Around the World</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=B00IGYQV6E" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Hal Roth
    - <a target="_blank" href="https://www.amazon.com/gp/product/007137616X/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=007137616X&linkCode=as2&tag=hundredrabbit-20&linkId=31b32cfe5726928783254fd1365fc06c">Seaworthy Offshore Sailboat</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=007137616X" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, John Vigor
    - <a target="_blank" href="https://www.amazon.com/gp/product/0071475087/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0071475087&linkCode=as2&tag=hundredrabbit-20&linkId=c12f9642d3a6f11f5084083e9a633d31">The Complete Anchoring Handbook</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=0071475087" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Poiraud Achim Ginsberg-Klemmt
  Travel Literature
    - <a target="_blank" href="https://www.amazon.com/gp/product/0918024765/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0918024765&linkCode=as2&tag=hundredrabbit-20&linkId=2824b0f623f0eb450f4b7dfe9f34e9a6">An Island to Oneself</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=0918024765" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Tom Neale
    - <a target="_blank" href="https://www.amazon.com/gp/product/076790446X/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=076790446X&linkCode=as2&tag=hundredrabbit-20&linkId=d5dce32f4a2b2c205739dbc8235a68df">North to the Night</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=076790446X" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Alvah Simon
    - <a target="_blank" href="https://www.amazon.com/gp/product/1770500375/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1770500375&linkCode=as2&tag=hundredrabbit-20&linkId=d18c9b054db9c976a157ab345252540c">The Curve of Time</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=1770500375" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Wylie Blanchet
    - <a target="_blank" href="https://www.amazon.com/gp/product/0451532163/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0451532163&linkCode=as2&tag=hundredrabbit-20&linkId=6abadbb330ac3ee06484a7987dd938ce">Walden and Civil Disobedience</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=0451532163" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Henry David Thoreau
    - <a target="_blank" href="https://www.amazon.com/gp/product/1613733488/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1613733488&linkCode=as2&tag=hundredrabbit-20&linkId=ab347d9ebee204d1b1c546bc1db2caef">The Box Wine Sailors</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hundredrabbit-20&l=am2&o=1&a=1613733488" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, Amy McCullough
  Documentaries
    - {{Life on a little wooden boat|https://vimeo.com/94842405}} 
    - {{Minimalism in a tiny home at sea|https://www.youtube.com/watch?v=CkaH_UUH0Ek}}
    - {{Untie the lines|https://www.youtube.com/watch?v=VERYUyO93_Y}}
`);

invoke.vessel.seal("dict","knowledge",payload);
